export const products = [
  {
    id: 1,
    name: "Product 1",
    imageUrl: "/images/product1.jpg",
    initialPrice: 100,
    finalPrice: 80,
  },
  {
    id: 2,
    name: "Product 2",
    imageUrl: "/images/product2.jpg",
    initialPrice: 120,
    finalPrice: 90,
  },
  {
    id: 3,
    name: "Product 3",
    imageUrl: "/images/product3.jpg",
    initialPrice: 80,
    finalPrice: 70,
  },
  {
    id: 4,
    name: "Product 4",
    imageUrl: "/images/product4.jpg",
    initialPrice: 150,
    finalPrice: 110,
  },
  {
    id: 5,
    name: "Product 5",
    imageUrl: "/images/product5.jpg",
    initialPrice: 150,
    finalPrice: 110,
  },
  {
    id: 6,
    name: "Product 6",
    imageUrl: "/images/product6.jpg",
    initialPrice: 150,
    finalPrice: 110,
  },
  {
    id: 7,
    name: "Product 7",
    imageUrl: "/images/product7.jpg",
    initialPrice: 150,
    finalPrice: 110,
  },
  {
    id: 8,
    name: "Product 8",
    imageUrl: "/images/product8.jpg",
    initialPrice: 150,
    finalPrice: 110,
  },
  {
    id: 9,
    name: "Product 9",
    imageUrl: "/images/product9.jpg",
    initialPrice: 150,
    finalPrice: 110,
  },
];
